Repository DSC-IIIT-Kalyani/ENCODN, pull requests merged in 2020-10, with the labels that each got.

#13 Update MORSECODE.py
  ENCODN/TOOLS/COMMUNICATION/TELECOM/MORSECODE/MORSECODE.py
Labels: hacktoberfest-accepted

#14 Update FRAME1BUTTON.py
  ENCODN/BUTTONS/FRAME1BUTTON.py
Labels: hacktoberfest-accepted

#17 Add BCD convertor
  ENCODN/TOOLS/ELECTRONICS/BCD/BCD.py
Labels: hacktoberfest-accepted

#19 Update ENCODN.py
  ENCODN/ENCODN.py
Labels: hacktoberfest-accepted

#20 Added SHA-1.py
  ENCODN/TOOLS/CRYPTOGRAPHY/MODERN CRPYTOGRAPHY/SHA-1/SHA-1.py
Labels: hacktoberfest-accepted

#28 Update README.md
  README.md
Labels: documentation

#30 Create Rozier cipher
  ENCODN/TOOLS/CRYPTOGRAPHY/OTHER/ROZIERCYPHER/ROZIER.py
Labels: hacktoberfest-accepted

#31 hashed values
  ENCODN/MD4.py
Labels: hacktoberfest-accepted

#33 Create Bacon cipher
  ENCODN/TOOLS/CRYPTOGRAPHY/OTHER/BACONCIPHER/BACON-FRAME.py
  ENCODN/TOOLS/CRYPTOGRAPHY/OTHER/BACONCIPHER/BACON.py
Labels: enhancement, hacktoberfest-accepted

#37 Create MODULOCALCULATOR.py
  ENCODN/TOOLS/MATHEMATICS/ARITHMETICS/MODULOCALCULATOR/MODULOCALCULATOR.py
Labels: hacktoberfest-accepted

#36 Update GAMEOFLIFE.py
  ENCODN/TOOLS/BIOLOGY/GAMEOFLIFE/GAMEOFLIFE.py
Labels: hacktoberfest-accepted

#34 Had an attempt at the logo, put in main directory
  ENCODN Logo.png
Labels: hacktoberfest-accepted
